sudo: required
services:
  - docker
language: node_js

node_js:
  - "lts/*"

script:
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome
  - npm run lint
  - npm test
  - npm run build
  - npm run test:integration
